@startuml
left to right direction

'user
actor "User" as user
note "Kodi user with\nVK.com accout" as n
    user . n

'search
rectangle "Search" <<package>> {
    user -- (Search videos)
    user -- (List searched videos)
    user -- (Search similar videos)
    user -- (List search history)
    user -- (Delete search)
}

@enduml