@startuml
left to right direction

'user
actor "User" as user
note "Kodi user with\nVK.com accout" as n
    user . n

'my videos
rectangle "My videos" <<package>> {
    user -- (List videos)
    user -- (Play video)
}

@enduml