@startuml
left to right direction

'user
actor "User" as user
note "Kodi user with\nVK.com accout" as n
    user . n

'my communities
rectangle "My communities" <<package>> {
   user -- (List communities)
   user -- (List community videos)
   user -- (Unfollow community)
}

@enduml