@startuml

actor "User" as user
participant "plugin.video.vk" as addon
participant "Kodi Python API" as kodipyapi
participant "VK OAuth2" as vkauth
participant "VK API" as vkapi

'list videos (simplified)
user -> addon : My videos
addon -> addon : Init
addon -> vkauth : createSession(token)
    addon <-- vkauth : session
addon -> vkauth : createAPI(session)
    addon <-- vkauth : api
addon -> vkapi : api.video.get(params)
    addon <-- vkapi : videos
addon -> kodipyapi : listitems(videos)
    user <-- kodipyapi : video list

@enduml
